import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@rfviolato/private-registry/font-awesome-5/css/fontawesome.min.css";
import "@rfviolato/private-registry/font-awesome-5/css/solid.min.css";
import "@rfviolato/private-registry/font-awesome-5/css/regular.min.css";

// fonts
import "typeface-roboto";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
